INSERT INTO jokes VALUES ( NULL, 'Chuck Norris threw a grenade and killed 50 people, then it exploded.');
INSERT INTO jokes VALUES ( NULL, 'Death once had a near-Chuck-Norris experience.');
INSERT INTO jokes VALUES ( NULL, 'Once a cobra bit Chuck Norris'' leg. After five days of excruciating pain, the cobra died.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can kill two stones with one bird.');
INSERT INTO jokes VALUES ( NULL, 'Chuck can set ants on fire with a magnifying glass. At night.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can hear sign language.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris makes onions cry.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris knows Victoria''s secret.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris counted to infinity. Twice.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris beat the sun in a staring contest.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris is the reason Waldo is hiding.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris is the only person that can punch a cyclops between the eye.');
INSERT INTO jokes VALUES ( NULL, 'Brett Favre can throw a football over 50 yards. Chuck Norris can throw Brett Favre even further.');
INSERT INTO jokes VALUES ( NULL, 'It is considered a great accomplishment to go down Niagara Falls in a wooden barrel. Chuck Norris can go up Niagara Falls in a cardboard box.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris plays russian roulette with a fully loded revolver... and wins.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can build a snowman out of rain.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can strangle you with a cordless phone.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris was once charged with three attempted murders in Boulder County, but the Judge quickly dropped the charges because Chuck Norris does not "attempt" murder.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris was once on Celebrity Wheel of Fortune and was the first to spin. The next 29 minutes of the show consisted of everyone standing around awkwardly, waiting for the wheel to stop.');
INSERT INTO jokes VALUES ( NULL, 'When Chuck Norris gives you the finger, he''s telling you how many seconds you have left to live.');
INSERT INTO jokes VALUES ( NULL, 'Giraffes were created when Chuck Norris uppercutted a horse.');
INSERT INTO jokes VALUES ( NULL, 'If it looks like chicken, tastes like chicken, and feels like chicken but Chuck Norris says its beef, then it''s beef.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can speak braille.');
INSERT INTO jokes VALUES ( NULL, 'Leading hand sanitizers claim they can kill 99.9 percent of germs. Chuck Norris can kill 100 percent of whatever the hell he wants.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can do a wheelie on a unicycle.');
INSERT INTO jokes VALUES ( NULL, 'Chuck actually died four years ago, but the Grim Reaper can''t get up the courage to tell him.');
INSERT INTO jokes VALUES ( NULL, 'When Chuck Norris was in middle school, his English teacher assigned an essay: "What is courage?" He received an A+ for turning in a blank page with only his name at the top.');
INSERT INTO jokes VALUES ( NULL, 'There is no theory of evolution, just a list of creatures Chuck Norris allows to live.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesn''t have good aim. His bullets just know better than to miss.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can pick oranges from an apple tree and make the best lemonade youve ever tasted.');
INSERT INTO jokes VALUES ( NULL, 'When a zombie apocalypse starts, Chuck Norris doesn''t try to survive. The zombies do.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can win tic-tac-toe in one turn.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris will never have a heart attack... even a heart isnt foolish enough to attack Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesnt wear a watch. He decides what time it is.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris beat Halo 1, 2, and 3 on Legendary with a broken Guitar Hero controller.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can kill your imaginary friends.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris''s computer has no "backspace" button, Chuck Norris doesn''t make mistakes.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris''s daughter lost her virginity, he got it back.');
INSERT INTO jokes VALUES ( NULL, 'The real reason Hitler killed himself is because he found out that Chuck Norris is Jewish.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris once went to mars. Thats why there are no signs of life.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris tells Simon what to do.');
INSERT INTO jokes VALUES ( NULL, 'The reason the Holy Grail has never been recovered is because nobody is brave enough to ask Chuck Norris to give up his favourite coffee mug.');
INSERT INTO jokes VALUES ( NULL, 'When Bruce Banner gets mad he turns into the Hulk. When the Hulk gets mad he turns into Chuck Norris. When Chuck Norris gets mad, run.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris sleeps with a pillow under his gun.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris''s Blood Type is AK-47.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesn''t play "hide-and-seek." He plays "hide-and-pray-I-don''t-find-you."');
INSERT INTO jokes VALUES ( NULL, 'When Chuck Norris enters a room, he doesn''t turn the lights on, he turns the dark off.');
INSERT INTO jokes VALUES ( NULL, 'M.C. Hammer learned the hard way that Chuck Norris can touch this.');
INSERT INTO jokes VALUES ( NULL, 'Bill Gates lives in constant fear that Chuck Norris'' PC will crash.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris is the only person on the planet that can kick you in the back of the face.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris'' dog is trained to pick up his own poop because Chuck Norris will not take shit from anyone.');
INSERT INTO jokes VALUES ( NULL, 'When the Boogeyman goes to sleep every night he checks his closet for Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesn''t cheat death. He wins fair and square.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris puts the "laughter" in "manslaughter".');
INSERT INTO jokes VALUES ( NULL, 'Chuck refers to himself in the fourth person.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris'' calendar goes straight from March 31st to April 2nd. No one fools Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesn''t dial the wrong number, you pick up the wrong phone.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris has a diary. It''s called the Guinness Book of World Records.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris once bowled a perfect game with a marble.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can hit you so hard your blood will bleed.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris CAN find the end of a circle.');
INSERT INTO jokes VALUES ( NULL, 'The only time Chuck Norris was wrong was when he thought he had made a mistake.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can drown a fish.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can unscramble an egg.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can cut a knife with butter.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can speak French... In Russian.');
INSERT INTO jokes VALUES ( NULL, 'A bulletproof vest wears Chuck Norris for protection.');
INSERT INTO jokes VALUES ( NULL, 'Big foot claims he saw Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'The saddest moment for a child is not when he learns Santa Claus isn''t real, it''s when he learns Chuck Norris is.');
INSERT INTO jokes VALUES ( NULL, 'Jack was nimble, Jack was quick, but Jack still couldn''t dodge Chuck Norris'' roundhouse kick.');
INSERT INTO jokes VALUES ( NULL, 'If you spell Chuck Norris wrong on Google it doesn''t say, "Did you mean Chuck Norris?" It simply replies, "Run while you still have the chance."');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris'' tears cure cancer. Too bad he has never cried.');
INSERT INTO jokes VALUES ( NULL, 'Some kids piss their name in the snow. Chuck Norris can piss his name into concrete.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris once walked away from a fight with two broken ribs and a dislocated arm. He hasn''t given them back yet...');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris once climbed Mt. Everest in 15 minutes, 14 of which he was building a snowman at the bottom.');
INSERT INTO jokes VALUES ( NULL, 'When Chuck Norris was born he drove his mom home from the hospital.');
INSERT INTO jokes VALUES ( NULL, 'Every Chuck Norris joke is a five star joke just because it says Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris gets 7 shots out of a revolver.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can make a slinky go upstairs.');
INSERT INTO jokes VALUES ( NULL, 'There is no such thing as fearless. Everyone fears Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'The original title for Alien vs. Predator was Alien and Predator vs Chuck Norris. The film was cancelled shortly after going into preproduction. No one would pay nine dollars to see a movie fourteen seconds long.');
INSERT INTO jokes VALUES ( NULL, 'When Chuck Norris looks in a mirror the mirror shatters, because not even glass is stupid enough to get in between Chuck Norris and Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'The reason newborn babies cry is because they know they have just entered a world with Chuck Norris.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can delete the Recycling Bin.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris CAN believe it''s not butter.');
INSERT INTO jokes VALUES ( NULL, 'Chuck can divide by zero.');
INSERT INTO jokes VALUES ( NULL, 'Superman owns a pair of Chuck Norris pajamas.');
INSERT INTO jokes VALUES ( NULL, 'A Handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.');
INSERT INTO jokes VALUES ( NULL, 'Police label anyone attacking Chuck Norris as a Code 45-11.... a suicide.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris went to a feminist rally and came back with his shirt ironed and holding a sandwich.');
INSERT INTO jokes VALUES ( NULL, 'The reason Superman changes outfits so fast in the phone booth is because Chuck Norris needed to make a call.');
INSERT INTO jokes VALUES ( NULL, 'Fear of spiders is called arachnophobia, fear of tight spaces is called claustrophobia, and fear of Chuck Norris is just plain logic.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris narrates Morgan Freeman''s life.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris can sit in the corner of a round room.');
INSERT INTO jokes VALUES ( NULL, 'If he wanted to, Chuck Norris could rob a bank. By phone.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris once smoked a cigarette, and the cigarette died of Chuck Cancer.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesn''t worry about high gas prices. His vehicles run on fear.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris doesn''t teabag , he potato sacks.');
INSERT INTO jokes VALUES ( NULL, 'Chuck Norris lost his virginity before his dad did.');
